### ISSUE TITLE
Start but show strange things, use another display

### ISSUE THREAD

**Issue by Cesar-S** [WRFleete/Arduino-CS1694#2]
Hello, I was pleased to find the only library for CS1694. Unfortunately on my board I can only start it, then it shows strange things.

I am using an E40201lf display, I couldn't find any reference of it.

Do you think that if I edit "`void CS1694 :: dispNum ....`" can I make it work?

br
Cesar

**Comment by WRFleete** [comment]
it is possible the segments may be arranged differently if you are using the numbers. 
could also be the 7 grids of 10 segments or  6 grids of 11 segs thing as well, I haven't been able to test with either of those as I only have the one board to work with

you will need to figure out which segments are attached to which segment drive etc
which will involve talking to the chip "raw" and modifying the table in the header file  which has the bit maps for the numbers etc (and possibly the dispNum routine as well)
it would help greatly if you draw a diagram of the display and which bits activate which segments then I may be able to make a new branch for your board/display :)

`sendtoCS1694(address); //address is 0xC0 to 0xCD `
`sendtoCS1694(n); //where n is 1,2,4,8,16,32,64,128 to test where each segment is`
`digitalWrite(_StrobePin,HIGH);`

**Comment by Cesar-S** [comment]
Thanks for the quick response, today I will look at the pcb and try to do the reading test too.  thank you i will inform you about the progress

**Comment by Cesar-S** [comment]
I'm not very good at programming, try from update display, modify 

```
CS1694 :: sendtoCS1694 (displayMem [i]);
```

by 
```
CS1694 :: sendtoCS1694 (my-num);
```
get results like these

```
NUM/SEG
1=F
2=EB
3=FEB
4=G
5=FD
6=BDE
7=BDEF
8= :
9=A:
10=BE
11=BEF:
12=D:
```

Although it gave me an idea, I took measurements on ic and display and obtained the results of the image, the use of the segment outputs starts at 2-3-4 ... and not 1-2-3-4 .. ..
key1 and key2 are connected by diode to S2 and S3, this doesn't work for me either.

![image](https://user-images.githubusercontent.com/4626896/72592160-bba1e300-38e0-11ea-9be2-e9cf70ce6ac7.png)

He told me to edit dispNum, could you give me some other clue according to the results?

From already thank you very much

**Comment by WRFleete** [comment]
figuring out the inputs might be difficult especially over the internet without physical access to the unit (it will probably involve modifying the library to return the unsigned long I use in the function that reads the inputs instead of the byte until I know what values to use) . getting the display working properly will be hard enough. I may have to figure out some code at this end (using my CS1694 and display set-up) that you can just copy into your editor to run on the arduino, to cycle through each combo and output to a serial terminal and you can just write down the memory location and data value that lights up something (the segment/LED advancing with a digital i/o on the arduino) and I may be able to figure out how to change the library a bit to show numbers etc with that particular arrangement  and control the LED and colon. I will reply later with some code

**Comment by WRFleete** [comment]
https://github.com/WRFleete/Arduino-CS1694/blob/CS1694-for-Cesar-S/examples/CS1694test-segcycle/CS1694test-segcycle.ino

ok if you load this (and set up the pins) when you pull pin5 to ground (for a little bit) it will advance, it should show 1 segment at a time and with the serial terminal open it will tell you which one it is testing. note the numbers and which segments/LED lights up.

**Comment by Cesar-S** [comment]
Ok, I already have the results, so it is much easier for me.
I had used another method and it didn't work.

I think I can modify the library, I will let you know when I have the results.
I just need to make the keys work, but for now I will concentrate on the display.

Thanks a lot

```
LED
---------
C3 1

DIG1
---------
C4 2	e 
C4 4	d
C4 16	c
C4 64	g
C4 128	a
C5 1	f
C5 2	b

DIG2
---------
C6 2	e 
C6 4	d
C6 16	c
C6 64	g
C6 128	a
C7 1	f
C7 2	b

DIG3
---------
CA 2	e 
CA 4	d
CA 16	c
CA 64	g
CA 128	a
CB 1	f
CB 2	b

DIG4
---------
C8 2	e 
C8 4	d
C8 16	c
C8 64	g
C8 128	a
C9 1	f
C9 2	b

COLON
---------
C6 8	 
CA 8
```

**Comment by WRFleete** [comment]
great. I will probably modify the library a little (I have a different branch for your particular board/setup) so the numbers etc should work once I add in the changes for your setup. 
at the moment if you use the alternate branch the displays shouldnt change but try the readButtons, the routine should return an unsigned long value when buttons are pressed. 
If you do something like `Serial.println(CS1694.readButtons())` the serial terminal should output the value read from the key matrix

**Comment by Cesar-S** [comment]
> If you do something like Serial.println(CS1694.readButtons()) the serial terminal should output the value read from the key matrix

I couldn't get results, just show 0

**Comment by WRFleete** [comment]
Did you use the modified library? 
https://github.com/WRFleete/Arduino-CS1694/tree/CS1694-for-Cesar-S?files=1

I modified it a little to return the raw unsigned long value.

**Comment by Cesar-S** [comment]
Sorry, use the above just download the example.
Now I try the complete library.

**Comment by WRFleete** [comment]
Later on I will apply the modifications that will show numbers on the 7 segments etc and probably add some functions to turn the LED and colons on/off. At the moment I will be away from a computer for a few hours

**Comment by Cesar-S** [comment]
I tried and I still get 0.

No problem, I know this is more of a challenge than something worthwhile, it just makes these old devices work 😄

**Comment by WRFleete** [comment]
give the updated library a test and load CS1694test2, it should start counting the millis variable and turn on the LED and colon. If you open the serial terminal it should return the value read from the key matrix

https://github.com/WRFleete/Arduino-CS1694/tree/CS1694-for-Cesar-S

**Comment by Cesar-S** [comment]
ok, great breakthrough, this works. 👏 👏 
LED, COLON and DIGITS ... only I think I made a mistake, I understand that the digits are from left to right 1234, now they are working as 4321 🤦‍♂  ....ps: (fixed)


The keys have no result, they remain in 0

**Comment by WRFleete** [comment]
ok looks like the inputs may not be working. I will reverse the order in the library for the digits

**Comment by WRFleete** [comment]
digit order reversed (hopefully). not sure why the inputs arent working correctly

**Comment by Cesar-S** [comment]
Ok, I had already made some changes and it worked, I will still check the library update.

the keys thing is weird ...

**Comment by Cesar-S** [comment]
Everything is displayed correctly.

With respect to the keys,
from **S3** there is a diode **->** to the common of **K1** and **K2**
from **S2** there is another diode **->** to the common of **K1** and **K2**

What I couldn't find is where it takes the value 0x46, I didn't see it in the datasheet

Know that I am very grateful for your work

**Comment by WRFleete** [comment]
the 0x46 sets the chip to read the key matrix
![readkey](https://user-images.githubusercontent.com/32031159/72662921-8668d280-3a51-11ea-8ecf-40fce667ace1.PNG)

**Comment by WRFleete** [comment]
it isnt using the key pins on the chip? that is possibly why the buttons arent working with my lib, it may be doing something funky 
![keypins](https://user-images.githubusercontent.com/32031159/72663014-9339f600-3a52-11ea-990f-3af748d5e85a.PNG)

**Comment by Cesar-S** [comment]
> it isnt using the key pins on the chip? 

yes

![image](https://user-images.githubusercontent.com/4626896/72663159-fd5c8780-39cd-11ea-904b-4bf2e30621c0.png)

**Comment by Cesar-S** [comment]
I already have a library running on XOD, based on its library.

Just need to polish details

![PrestigiousWeeklyGosling-size_restricted 1](https://user-images.githubusercontent.com/4626896/72663196-5a583d80-39ce-11ea-82af-7b4d95444e96.gif)

**Comment by WRFleete** [comment]
ok, i've run the test sketch (using your library so my display looks weird) but bridging the same pins on my chip and the serial dump shows some numbers, it may be a defective chip or switches or the diodes are messing with things 
5+9 outputs an 8. 6+9 outputs 16. 10+5 outputs 256, 10+6 outputs 512

**Comment by Cesar-S** [comment]
It may be, I will do that test later, I am without sleep I have passed by today.

I will do these tests between today and tomorrow and will notify you of results.

thanks for your time

**Comment by Cesar-S** [comment]
Perform direct tests 5-9 / 5-10 and 6-9 / 6-10 without results.
It must be the damaged chip, I would have to look if I have another.

But the main and most important thing already works, I only have one question regarding the position of the digits.
The TM1637 libraries take 0-1-2-3 in that order, in this case it is by the library address?

As I mentioned before, I adapted it to XOD, and to multiplex the digits I made a node that works for TM1637.
The idea was to use the same for both libraries.

I don't know if you know XOD or not, there are many who prefer traditional programming, in my case it helped me learn to program in C ++.
Could I send you a library for you to test if the keys work? The idea is to make a complete library based on your library.

![lm75-cs1694](https://user-images.githubusercontent.com/4626896/72671467-76d59380-3a29-11ea-95c6-85f4713ce7a3.png)

**Comment by WRFleete** [comment]
No I am not familiar with XOD.
I've written the dispNum routine to take a number from 0-36 (zero indexed, 0-9 directly shows numbers, 10 and higher do alphabet characters and some symbols where letters cant be shown in 7 segments) and a zero index "display address" 0 being the rightmost digit.

**Comment by Cesar-S** [comment]
> No I am not familiar with XOD

If you want I can help you with whatever you need, you can find me on the forum.

I will follow the library closely, seeing the changes but with the objective achieved.
I will also need to edit some steps to adapt it to XOD.

👍

**Comment by Cesar-S** [comment]
As I promised here I leave a test file from the library, open **cs1694-dev** just uncomment the line and comment the following.
The program will download the library compatible with your display from its repository. 
Connect your board and use upload & debug, repeat the process after downloading, you will also request the download of arduino repository.

The xod library will download automatically when you open the patch
```
`//#pragma XOD require "https://github.com/WRFleete/Arduino-CS1694"
#pragma XOD require "https://github.com/Cesar-S/Arduino-CS1694" //library modified for E40201LF display and two led.`
```

[testing-cs1694.zip](https://github.com/WRFleete/Arduino-CS1694/files/4082313/testing-cs1694.zip)
